# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DHCP-Info
version:      0.01
version_from: lib/Net/DHCP/Info.pm
installdirs:  site
requires:
    DateTime:                  0
    NetAddr::IP:               0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
