---
abstract: 'Fast dhcpd.leases and dhcpd.conf parser'
author:
  - 'Jan Henning Thorsen, C<< <pm at flodhest.net> >>'
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-DHCP-Info
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  NetAddr::IP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
